import { formatTime, taskProgress, taskStatus } from '../services/taskService'
function TaskRow({ task, parent, now, onToggle, onDeadline }) {
  const status = taskStatus(task, now)
  const grouped = !parent && task.subtasks?.length > 0
  return <div className="task-row"><input type="checkbox" checked={task.completed} disabled={grouped} onChange={() => onToggle(parent?.id || task.id, parent ? task.id : undefined)} aria-label={`Hoàn thành: ${task.title}`} title={grouped ? 'Hoàn thành tất cả task con để hoàn thành task chính' : undefined} /><div className="task-details"><strong className={task.completed ? 'completed-title' : ''}>{task.title}</strong><small>Hạn: {formatTime(task.dueDate)}</small><span className={`task-status ${status.kind}`}>{status.text}</span>{task.completedAt && <small>Hoàn thành lúc: {formatTime(task.completedAt)}</small>}<details className="deadline-editor"><summary>Đổi thời hạn</summary><form onSubmit={(e) => { e.preventDefault(); onDeadline(parent?.id || task.id, parent ? task.id : undefined, new FormData(e.currentTarget).get('dueDate')) }}><input aria-label={`Thời hạn ${task.title}`} name="dueDate" type="datetime-local" defaultValue={task.dueDate.length === 10 ? `${task.dueDate}T23:59` : task.dueDate} required /><button className="task-text-button" type="submit">Lưu hạn</button></form></details></div>{!parent && <span className={`priority ${task.priority === 'high' ? 'high' : ''}`}>{task.priority === 'high' ? 'Quan trọng' : 'Bình thường'}</span>}</div>
}
export function TaskList({ tasks, filter, onFilter, query, onQuery, onToggle, onDeadline, now }) {
  return <section className="home-card task-section" aria-labelledby="task-heading"><div className="section-title"><h2 id="task-heading">Công việc của bạn <span>{tasks.length}</span></h2></div><div className="task-toolbar"><div className="task-tabs" aria-label="Lọc công việc">{[['all', 'Tất cả'], ['pending', 'Chưa xong'], ['overdue', 'Quá hạn'], ['completed', 'Hoàn thành']].map(([value, label]) => <button key={value} aria-pressed={filter === value} onClick={() => onFilter(value)}>{label}</button>)}</div><input aria-label="Tìm công việc" className="task-search" placeholder="Tìm task chính / con…" value={query} onChange={(e) => onQuery(e.target.value)} /></div>
    {tasks.length ? <ul className="task-list task-tree">{tasks.map((task) => <li key={task.id}><TaskRow task={task} now={now} onToggle={onToggle} onDeadline={onDeadline} />{task.subtasks.length > 0 && <div className="subtask-group"><div className="task-progress-label"><span>{task.subtasks.filter((s) => s.completed).length}/{task.subtasks.length} bước hoàn thành</span><strong>{taskProgress(task)}%</strong></div><progress max="100" value={taskProgress(task)} aria-label={`Tiến độ ${task.title}`} /><p className="task-helper">Task chính tự hoàn thành khi tất cả bước đã xong.</p><ul>{task.subtasks.map((child) => <li key={child.id}><TaskRow task={child} parent={task} now={now} onToggle={onToggle} onDeadline={onDeadline} /></li>)}</ul></div>}</li>)}</ul> : <div className="task-empty"><div>✓</div><h3>{query || filter !== 'all' ? 'Chưa có công việc phù hợp' : 'Một khởi đầu thật nhẹ nhàng'}</h3><p>Thêm công việc hoặc thử đổi bộ lọc và từ khóa.</p></div>}
  </section>
}
export function TaskNotifications({ tasks, now }) {
  return <section className="home-card task-notifications"><h2>Thông báo công việc</h2><p className="task-helper">Cập nhật khi đang mở trang công việc hoặc khi quay lại. Task chưa xong được ghi chú ngay trong danh sách.</p><div aria-live="polite" aria-relevant="additions text">{tasks.length ? <ul>{tasks.map((task) => <li key={task.id}><strong>{task.title}</strong>{task.parentTitle && <small>Thuộc: {task.parentTitle}</small>}<span className={`task-status ${taskStatus(task, now).kind}`}>{taskStatus(task, now).text}</span><small>Hạn: {formatTime(task.dueDate)}</small></li>)}</ul> : <p className="task-helper">Chưa có thông báo hoàn thành hoặc quá hạn.</p>}</div></section>
}
